quarkus:
  http:
    port: 9091
  log:
    level: INFO
    category:
      "com.quarkus.database":
        level: TRACE
      "com.quarkus.controller":
        level: DEBUG
      "com.quarkus.service":
        level: DEBUG
    console:
      enabled: true
      level: TRACE
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
  rest-client:
    third-party-api:
      url: "http://localhost:${quarkus.http.port}"
      scope: "javax.inject.Singleton"                   # Scope CDI del cliente, ej. javax.inject.Singleton o javax.enterprise.context.ApplicationScoped.
      connect-timeout: 3000                             # Timeout para establecer la conexi칩n HTTP.
      read-timeout: 8000                                # Timeout para leer la respuesta.
  #    providers:                                       # Lista de clases proveedoras (ej. filtros, interceptores JAX-RS).
  #      - com.ejemplo.MyCustomProvider
  #    followRedirects: true                            # Si debe seguir redirecciones HTTP 3xx.
  #    proxyAddress: my.proxy.com:8080                  # Proxy para las conexiones HTTP.
  #    disableSslVerification: false                    # Si se debe desactivar la verificaci칩n SSL.
  #    trustStore: /path/to/truststore                  # Ruta del truststore (para certificados SSL).
  #    trustStorePassword: secret                       # 	Contrase침a del truststore.
  #    keyStore: /path/to/keystore                      # Ruta del keystore (para cliente mutual TLS).
  #    keyStorePassword: secret                         # Contrase침a del keystore.
  #    hostnameVerifier: com.ejemplo.MyHostNameVerifier # Clase HostnameVerifier personalizada.

